sudo: false
language: php
php:
  - '5.3'
before_script:
  - export TZ='UTC'
  - composer self-update
  - composer update
script:
  ./vendor/bin/phpunit --configuration phpinit.xml --testsuite UnitTest